[build]
  # No build command needed for this project
  command = ""
  # Publish the frontend directory directly
  publish = "frontend/"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE_API_URL = "https://stock-prection-v2.onrender.com"

[dev]
  command = "cd frontend && npm run dev"
  port = 3001
  targetPort = 3001
  publish = "frontend/dist"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; img-src 'self' data: http: https:; connect-src 'self' https://*.netlify.app https://*.netlify.com https://*.netlify-functions.net http://localhost:* https://api.polygon.io https://stock-prection-v2.onrender.com https://prediction-ai-stock-scrimba.netlify.app;"

# CORS headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy API requests to your backend
[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/api/:splat"
  status = 200
  force = true
