services:
  - type: web
    name: stock-prediction-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: POLYGON_API_KEY
        sync: false  # Set this in the Render dashboard
    plan: free
    region: oregon  # Or choose a region closer to you
